export const enum REDUCER_ACTION_TYPE {
  OPEN_MENU,
  CLOSE_MENU,
  TOGGLE_CART,
  OPEN_LIGHTBOX,
  CLOSE_LIGHTBOX,
  NEXT_SLIDE,
  BACK_SLIDE,
  ADD_TO_CART,
  REMOVE_ITEM,
  INCREASE,
  DECREASE,
}
